[tool.poetry]
name = "pius"
version = "0.1.2"
description = "A library to write Gerber files"
authors = ["alaindef <alain.de.feyter@gmail.com>"]
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
